proxyOrder: 0
profileParsersText: |
  parsers:
    # - reg: .*www\.example\.com.*$
    # - reg: .*example.*q=subscription$
    - reg: ^((?!www\.example\.com).)*$
      file: 'D:/Applications/cfw-scripts/scripts/change-keys.js'
    - reg: ^((?!www\.example\.com).)*$
      file: 'D:/Applications/cfw-scripts/scripts/change-rules.js'
    - reg: ^((?!www\.example\.com).)*$
      file: 'D:/Applications/cfw-scripts/scripts/merge-nodes.js'
    - reg: ^((?!www\.example\.com).)*$
      file: 'D:/Applications/cfw-scripts/scripts/change-rules.yml'
    - reg: ^((?!www\.example\.com).)*$
      file: 'D:/Applications/cfw-scripts/scripts/subs-info-parser.js'
    - reg: ^((?!www\.example\.com).)*$
      file: 'D:/Applications/cfw-scripts/scripts/auto-check-in.js'
selectAfterUpdated: false
profilePath: '%HOMEPATH%\.config\clash\profiles' # 此处需要更改！！！
headersText: |
  headers: # object
mixinCode: |-
  module.exports.parse = ({ content, name, url }, { axios, yaml, notify }) => {
   const extra = {
     dns: {
       enable: true,
       listen: ':53',
       nameserver: ['8.8.8.8']
     }
   }
   return { ...content, ...extra }
  }
mixinText: |+
  mixin: # object
    hosts:
      'phicomm.me': 192.168.2.1
    dns:
      enable: true
      ipv6: false
      listen: 0.0.0.0:53
      enhanced-mode: redir-host
      use-hosts: true
      fake-ip-filter:
        - 'dns.msftncsi.com'
        - 'www.msftncsi.com'
        - 'www.msftconnecttest.com'
        - '+.qq.com'
        - '+.music.163.com'
        - '+.music.162.com'
      default-nameserver:
        - 119.29.29.29
        - 114.114.114.114
        - 8.8.8.8
      nameserver:
        - 119.29.29.29
        - 223.5.5.5
        - 8.8.8.8
        - 1.1.1.1
      fallback:
        - 'https://1.1.1.1/dns-query'
        - 'https://162.159.36.1/dns-query'
        - 'https://162.14.13.12/dns-query'
        - 'tls://dns.rubyfish.cn:853'
        - 'tls://1.0.0.1:853'
        - 'tls://dns.google:853'
      fallback-filter:
        geoip: true
        ipcidr:
          - 0.0.0.0/32
          - 127.0.0.0/8
          - 240.0.0.0/4

showNotifications: true
theme: 0
systemTheme: true
latencyUrl: http://www.gstatic.com/generate_204
connProxy: 0
connProfile: true
connMode: false
connKeepOld: false
bypassText: |
  bypass:
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
mixinType: 0
interfaceName: 以太网
showNewVersionIcon: true
systemProxyTypeIndex: 0
pacContentText: |-
  var host = "127.0.0.1:7890";
  var Socks5 = "SOCKS5 " + host +"; ";
  var Proxy = "PROXY " + host +"; ";
  var Direct = "DIRECT; ";
  function FindProxyForURL(url, host) {
    return Socks5 + Proxy + Direct;
  }
shortcutSystemProxy: ''
shortcutMixin: ''
editor: 1
showProxyFilter: true
shortcutGlobalMode: ''
shortcutRuleMode: ''
hideAfterStartup: true
proxyItemWidth: ''
childProcessText: |-
  processes: # array
    - command: subconverter.exe  # 程序名称
      options:
        cwd: D:\Applications\subconverter # 子进程工作目录
        windowsHide: false
randomControllerPort: false
